project:
  type: book  
  execute-dir: project
  

book:
  ## Metadatos
  title: "Introducción a la Revisión sistemática con meta-análisis"
  author: "Instituto Nacional de Epidemiología Dr. Juan H. Jara"
  

  ## Configuración
  page-footer: 
    center: Este material fue creado en <a href="https://quarto.org/">Quarto</a> y forma parte del curso de Introducción a la Revisión sistemática con meta-análisis © 2026 Instituto Nacional de Epidemiología "Dr. Juan H. Jara" (ANLIS)
    right: <img src="../logos/logos_ine.svg" height="30">
  
  output-file: "rev_sis_ma"
  cover-image: images/meta-analysis_fusion.jpeg
  downloads: [pdf, epub]

  ## Barra lateral
  sidebar: 
    style: docked
    # logo: logos/logo_curso.png
    pinned: true
    tools: 
      - icon: r-circle-fill
        menu: 
          - text: R para Windows
            icon: windows
            target: _blank
            href: https://cran.rstudio.com/bin/windows/
          - text: R para macOS
            icon: apple
            target: _blank
            href: https://cran.rstudio.com/bin/macosx/
          - text: R para Linux
            icon: ubuntu
            target: _blank
            href: https://cran.rstudio.com/bin/linux/
          - text: RStudio Desktop
            icon: terminal
            target: _blank
            href: https://posit.co/download/rstudio-desktop/
          - text: RTools
            icon: terminal
            target: _blank
            href: https://cran.r-project.org/bin/windows/Rtools/
      - icon: file-zip
        menu: 
          - text: Paquetes para el curso
            icon: file-zip
            target: _blank
            href: files/paquetes_curso.zip
          - text: Datos de ejemplo
            icon: file-zip
            href: files/datos.zip
      
            
  ## Capítulos
  chapters:
  - text: "Prefacio"
    icon: book
    href: index.qmd

  - part: "Introducción"
    icon: file-earmark-bar-graph
    chapters:
      - "extras/intro_inferencia.qmd"
      - "extras/intro_R.qmd"

  - part: "Meta-análisis"
    icon: file-earmark-bar-graph
    chapters: 
        - "unidad_2/01_intro.qmd"
        - "unidad_2/02_fixed_random.qmd"
        - "unidad_2/03_MA_descriptivos.qmd"
        - "unidad_2/04_MA_analiticos.qmd"
        - "unidad_2/05_moderadores.qmd"
        - "unidad_2/06_MA_multinivel.qmd"
        # - "unidad_2/07_pub_bias.qmd"

## Botón de anterior/siguiente
page-navigation: true
  
## Botón de volver arriba
back-to-top-navigation: true

## Números de sección
number-sections: false

## Referencias
bibliography: references.bib

## Opciones de formato
format:
  html:
    # Tema claro y oscuro
    theme: 
     light: cosmo
     dark: cyborg
        
    # CSS
    css: styles.css
    
    grid:
      sidebar-width: 300px

  # epub:
  # #   cover-image: logos/logo_curso.png

  # typst: 
  #   toc: false
  #   include-in-header: typst-header.typ
  #   lang: es
  #   papersize: a4
  #   margin: 
  #     left: 2cm
  #     top: 2cm

# Tipografía
mainfont: "Calibri"

# Archivos para descargar
resources: 
  - files/
  
# Idioma del documento
lang: es

# Salida código de R
execute: 
  echo: true
  warning: false
  freeze: auto
  
# Metadatos
license: CC BY-NC

# Autores
author: 
  - name: Tamara Ricardo
    orcid: 0000-0002-0921-2611  
